export const projects = [
  {
    title: 'Memory Game',
    description: "Match cards to get points, player with most matches wins!",
      image: '/images/memory.png',
      tags: ['React'],
    source: 'https://memory-game-app-psi.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/memorygame',
    id: 0,
  },

  {
    title: 'Crypto API Website',
    description: "Responsive Crypto site built using Axios API.",
      image: '/images/crypto.png',
      tags: ['React', 'Json'],
    source: 'https://crypto-ranking-api-app.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/crypto-api-website',
    id: 1,
  },
  {
    title: 'Tic Tac Toe',
    description: "Find out who is the best at Tic-Tac-Toe.",
    image: '/images/tictac.png',
    tags: ['React'],
    source: 'https://ahmedwaly0000.github.io/tictactoeGAME/',
    visit: 'https://github.com/AhmedWaly0000/tictactoeGAME',
    id: 2,
  },
  {
    title: 'Dice Roll',
    description: "Dice is rolled, highest number wins.",
    image: '/images/dice.jpeg',
    tags: ['JavaScript'],
    source: 'https://dice-game-alpha-two.vercel.app/',
    visit: 'https://AhmedWaly0000/DiceGame',
    id: 3,
  },
  {
    title: 'Simon Says',
    description: "Keep track of Simon's color sequence or fail.",
    image: '/images/simon.jpeg',
    tags: ['Javascript'],
    source: 'https://simon-game-drab.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/SimonGame' ,
    id: 4,
  },
  {
    title: 'Drum Kit',
    description: "Play Drums online.",
    image: '/images/drum-kit.jpeg',
    tags: ['JavaScript'],
    source: 'https://drum-kit-nu-coral.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/DrumKit',
    id: 5,
  },
  {
    title: 'Snakes and Ladders',
    description: "Play Snakes and Ladders online online.",
    image: 'public/images/snakesandLadders.png',
    tags: ['JavaScript'],
    source: 'https://snakes-and-ladders-project.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/SnakesAndLadders-Project',
    id: 6,
  },
  {
    title: 'Connect 4',
    description: "Play Connect 4 online.",
    image: 'public/images/connect4.png',
    tags: ['JavaScript'],
    source: 'https://connect-4-project.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/Connect-4-Project',
    id: 6,
  },
  {
    title: 'Chess',
    description: "Play Chess online.",
    image: '/Users/ahmed.waly/Desktop/Coding Projects/Ahmed-s-Portfolio-Website-master/public/images/chess.png',
    tags: ['JavaScript'],
    source: 'https://chess-project-mauve.vercel.app/',
    visit: 'https://github.com/AhmedWaly0000/Chess-Project',
    id: 7,
  }
];


export const TimeLineData = [
  { year: 2017, text: 'Sdsdsad', },
  { year: 2018, text: 'dasdsdsa', },
  { year: 2019, text: 'dsadsd', },
  { year: 2020, text: 'fddsfdf', },
  { year: 2021, text: 'fggfdgfddf', },
];